name = "HyperHessians"
uuid = "06b494a0-c8e0-40cc-ad32-d99506a00a6c"
version = "0.1.0"
authors = ["KristofferC <kcarlsson89@gmail.com>"]

[deps]
CommonSubexpressions = "bbf7d656-a473-5ed7-a52c-81e309532950"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[weakdeps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
HyperHessiansDiffResultsExt = "DiffResults"
HyperHessiansStaticArraysExt = "StaticArrays"

[compat]
CommonSubexpressions = "0.3"
DiffResults = "1.1.0"
DiffTests = "0.1.2"
ForwardDiff = "1.3.0"
SIMD = "3"
julia = "1.10"

[extras]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
DiffTests = "de460e47-3fe3-5279-bb4a-814414816d5d"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DiffTests", "ForwardDiff", "StaticArrays", "Test", "DiffResults"]
